### ISSUE TITLE
How do get pandas added to pre-existing notebook kernel

### ISSUE THREAD

**Issue by swrneale** [NCAR/GeoCAT#10]
I am using the pre-loaded python conda environments as a kernel in a jupyter notebook and wondered whether geocat existed in any of these pre loaded environments or how could I easily add it to one. I hope I don't have to create a new one for this. The installation page seemed a little minimal on information for this. Thanks Rich

**Comment by erogluorhan** [comment]
Hi Rich!

Sorry for missing your issue for a long while!

I am assuming you are using NCAR's JupyterHub so that the same issue should still be existing (Please let me know if otherwise). If so, we are currently working on either providing GeoCAT in one of those pre-loaded kernels (maybe a brand new one would be created) or providing a GeoCAT conda environment file that can be used to create individual conda environments in NCAR's HPC systems and to use that from within JupyterHub.

Please let me know if anything further needs to be discussed.

Orhan - GeoCAT
