### ISSUE TITLE
GeoCAT homepage video lost 

### ISSUE THREAD

**Issue by erogluorhan** [NCAR/GeoCAT#61]
We lost track of the GeoCAT video that had been streamed on GeoCAT [homepage](https://geocat.ucar.edu/).

Hi @michaelavs , do you happen to have it in your personal records?

**Comment by michaelavs** [comment]
I don't but it should be on the GeoCAT youtube page. I don't fully recall the login information for that (I believe I put it in a shared file in the GeoCAT team drive when I created the account), but I was able to find the video here: https://www.youtube.com/watch?v=-ElqWVIAXpI

It looks like the video (and maybe account) was taken over by someone else in NCAR, so that may be why the video disappeared.

**Comment by pilotchute** [comment]
The Youtube account was associated with your ucar.edu email (which was deleted, along with all it's associated google (and youtube is google) accounts)
So I think it must be gone.
_
Alea Kootz | NCAR | CISL | VAST | GeoCAT
(she/her/hers)
***@***.***
719-358-3362

While working from home, our working hours may be different, no need to reply outside of your working hours.

**Comment by erogluorhan** [comment]
> I don't but it should be on the GeoCAT youtube page. I don't fully recall the login information for that (I believe I put it in a shared file in the GeoCAT team drive when I created the account), but I was able to find the video here: https://www.youtube.com/watch?v=-ElqWVIAXpI
> 
> It looks like the video (and maybe account) was taken over by someone else in NCAR, so that may be why the video disappeared.

Thanks, Michaela! It is lost as Alea describe, but it's great to know there was a copy of it at the other channel you linked. We can get help from that channel.

**Comment by erogluorhan** [comment]
@pilotchute For now, I linked the homepage to the video @michaelavs found to fix the issue. For the long term, I agree with your new video thoughts.
