### ISSUE TITLE
fail to install GeoCAT-comp on windows 10

### ISSUE THREAD

**Issue by alvistock** [NCAR/GeoCAT#9]
Hi, I had  succeed installed  miniconda, but when input the command  “conda create -n geocat -c conda-forge -c ncar geocat-comp”，it's show a error，the error information is:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: |
Found conflicts! Looking for incompatible packages.

This can take several minutes.  Press CTRL-C to abort.
Examining @/win-64::__cuda==10.2=0:  50%|████████████████▌                | 1/2 [00:00<0Examining @/win-64::__cuda==10.2=0: 100%|████████████████████████████████failed

UnsatisfiableError: The following specifications were found to be incompatible with your CUDA driver:

  - feature:/win-64::__cuda==10.2=0

Your installed CUDA driver is: 10.2

**Comment by pilotchute** [comment]
Currently there is no conda package for geocat-comp on the ncar channel for windows systems. 
Because we use a compiled fortran library, the compiled result is operating system dependent. We currently support Darwin (MacOSX) and Linux, we do not at the moment provide binaries for windows, but we are looking into it. 
If you have a windows machine, you should be able to access a unbuntu based kernel by calling "bash" from the cmd.exe program. This will put you in a command line linux environment where you could install and run conda on linux, and thus the linux package foe geocat-comp.

**Comment by alvistock** [comment]
Thanks very much,  
hope  to see  it's  work on the windows  soon.













--

Mr.Yu yijun
YinJiang MET office, LongJin Street, YinJiang county
GuiZhou Prov. China 555200.
Call: (86)18932069299
Nice day
God Bless you!






At 2020-06-26 03:56:36, "Austin Kootz" <notifications@github.com> wrote:

Currently there is no conda package for geocat-comp on the ncar channel for windows systems.
Because we use a compiled fortran library, the compiled result is operating system dependent. We currently support Darwin (MacOSX) and Linux, we do not at the moment provide binaries for windows, but we are looking into it.
If you have a windows machine, you should be able to access a unbuntu based kernel by calling "bash" from the cmd.exe program. This will put you in a command line linux environment where you could install and run conda on linux, and thus the linux package foe geocat-comp.
